/** 对比页数据 — 与 tools.json 对齐，新增工具时需同步更新 */
export const categories = [
  { key: "type", label: "类型" },
  { key: "price", label: "价格" },
  { key: "model", label: "AI 模型" },
  { key: "install", label: "安装难度" },
  { key: "china", label: "国内直连" },
  { key: "git", label: "Git 集成" },
  { key: "files", label: "文件操作" },
  { key: "sandbox", label: "安全沙箱" },
  { key: "plugins", label: "扩展生态" },
  { key: "bestFor", label: "最适合" },
];

export interface CompareTool {
  name: string;
  slug: string;
  color: string;
  data: Record<string, string>;
}

export const tools: CompareTool[] = [
  {
    name: "Claude Code",
    slug: "claude-code",
    color: "var(--color-accent)",
    data: {
      type: "CLI 命令行",
      price: "DeepSeek低价 / Claude需API Key",
      model: "DeepSeek / Claude / 第三方",
      install: "中等",
      interface: "终端交互",
      china: "✅ 可直连（需配置）",
      git: "✓ 深度集成",
      files: "✓ 直接读写",
      sandbox: "手动开启",
      plugins: "MCP + Plugins + Hook + Skill",
      bestFor: "全栈开发 · 项目管理 · Git 工作流",
    },
  },
  {
    name: "Codex CLI",
    slug: "codex",
    color: "hsl(160,70%,52%)",
    data: {
      type: "CLI 命令行",
      price: "ChatGPT订阅 或 API按量计费",
      model: "GPT-4o / GPT-5 / o3",
      install: "中等",
      interface: "终端交互",
      china: "需中转或 VPN",
      git: "✓ 支持",
      files: "沙箱内操作",
      sandbox: "默认开启",
      plugins: "Plugins（90+） + MCP + Skills",
      bestFor: "ChatGPT 用户 · 沙箱安全需求",
    },
  },
  {
    name: "Cursor",
    slug: "cursor",
    color: "hsl(265,75%,64%)",
    data: {
      type: "IDE 桌面应用",
      price: "免费版 / Pro $20/月",
      model: "GPT-4 / Claude / 自定义",
      install: "简单",
      interface: "图形化 IDE",
      china: "✓ 直连",
      git: "✓ VS Code 级别",
      files: "✓ IDE 原生",
      sandbox: "不适用",
      plugins: "VS Code 扩展",
      bestFor: "IDE 用户 · 代码补全 · UI 开发",
    },
  },
  {
    name: "Copilot",
    slug: "copilot",
    color: "hsl(42,96%,64%)",
    data: {
      type: "IDE 扩展",
      price: "个人版 $10/月 · 30天免费试用",
      model: "GPT-4",
      install: "简单",
      interface: "编辑器内联",
      china: "✓ 直连",
      git: "✅ 基础支持",
      files: "✓ Agent 模式 / 多文件编辑",
      sandbox: "不适用",
      plugins: "VS Code / JetBrains + MCP",
      bestFor: "代码补全 · 新手友好 · 已有 IDE",
    },
  },
  {
    name: "Windsurf",
    slug: "windsurf",
    color: "hsl(218,80%,62%)",
    data: {
      type: "IDE 桌面应用",
      price: "免费版 / Pro $15/月",
      model: "GPT-4 / Claude / 自定义",
      install: "简单",
      interface: "图形化 IDE",
      china: "✓ 直连",
      git: "✓ VS Code 级别",
      files: "✓ 多文件编辑",
      sandbox: "不适用",
      plugins: "VS Code 扩展",
      bestFor: "多文件编辑 · VS Code 迁移 · IDE 用户",
    },
  },
  {
    name: "Cline",
    slug: "cline",
    color: "hsl(190,80%,48%)",
    data: {
      type: "VS Code 扩展 / CLI",
      price: "取决于所选 API 供应商",
      model: "20+ 提供商自由选择",
      install: "中等",
      interface: "VS Code 侧栏 / 终端",
      china: "✅ 可直连（配 DeepSeek 等国产模型）",
      git: "✓ 支持",
      files: "✓ 多文件编辑",
      sandbox: "手动开启（Plan/Act 分离）",
      plugins: "MCP 协议 + 多代理",
      bestFor: "MCP 深度用户 · 多模型需求 · 自动化",
    },
  },
  {
    name: "GitHub Spark",
    slug: "github-spark",
    color: "hsl(270,70%,60%)",
    data: {
      type: "Web 应用",
      price: "需 GitHub Copilot 订阅",
      model: "Copilot 内置模型",
      install: "简单",
      interface: "浏览器",
      china: "✓ 直连",
      git: "− 不直接操作",
      files: "− 生成独立应用",
      sandbox: "不适用",
      plugins: "代码导出到 GitHub 仓库",
      bestFor: "非开发者 · 原型制作 · 零代码应用",
    },
  },
];
